### ISSUE TITLE
Getting error  Call to undefined method BitWasp\Bitcoin\Script\Script::getOutputScript()

### ISSUE THREAD

**Issue by bilginm** [evias/blockchain-cli#3]
First of all thanks for the implementation. 

I have a problem when i try to recover a USDT fund. I am using "copay-recovery" command but i am getting  Call to undefined method BitWasp\Bitcoin\Script\Script::getOutputScript() error.

The command i execute is:
`php application omni:copay-recovery --input1="33itMqP2QngTbiR4ydS2hhNn1gRWGV3ULr" --vindex1="1" --cosig1="treat float add crouch trash decide mirror alert debris race evil coach obvious used torch" --cosig2="badge toe bid hurdle forum motion half talk file mirror mind night arrange spray unveil" --destination "1PXP46i4MxPQjzMr9uxtTY9dRWYj8rFqWN" --change "33itMqP2QngTbiR4ydS2hhNn1gRWGV3ULr" --min 2 --path-sign1="m/44'/0'/0'/0/2" --path-sign2="m/44'/0'/0'/0/2" --colored-op="6f6d6e69000000000000001f00000003e82a7b00"`

The error i get at line:
`395:         $m1_outputScript = $m1_P2SHScript->getOutputScript();`

The mnemonics are totally random they dont matter but the error i get simply says that the generated redeemscript is not instaceof type P2shScript. Why is that? How can i get this this code to work?

**Comment by evias** [comment]
Hey there,

sorry for the late reply .. 

From what I can see, the latest version of P2SHScript class under BitWasp/Script/Script/P2shScript still has the `getOutputScript()` method. I would think maybe your m1 is not a P2shScript ? If it is not, you might need to call the `getRedeemScript()` method instead.

Alternatively I would try the following : 

```
$outputScript = ScriptFactory::scriptPubKey()->payToScriptHash($m1_P2SHScript->getScriptHash());
```

Unsure if it would work, but that is approx. what is done in the P2shScript class.

**Comment by bilginm** [comment]
> Hey there,
> 
> sorry for the late reply ..
> 
> From what I can see, the latest version of P2SHScript class under BitWasp/Script/Script/P2shScript still has the `getOutputScript()` method. I would think maybe your m1 is not a P2shScript ? If it is not, you might need to call the `getRedeemScript()` method instead.
> 
> Alternatively I would try the following :
> 
> ```
> $outputScript = ScriptFactory::scriptPubKey()->payToScriptHash($m1_P2SHScript->getScriptHash());
> ```
> Unsure if it would work, but that is approx. what is done in the P2shScript class.

The address i am using is a multi signature address that's why i assumed it is P2SHScript. I will try my `getRedeemScript()` perhaps it'll work. I will also check my m1. I might have done some mistake about that input. 

My original problem is same as yours but i have the multisig keys of the HD wallet for that derivation while i dont have the mnemonic. But having the multisig privatekeys are better i guess. I am just doing some changes in your code to make it work. 

Thanks for the reply. I'll keep you posted if i can make it work.
