### ISSUE TITLE
Can I use this tool?

### ISSUE THREAD

**Issue by ekkis** [evias/blockchain-cli#4]
I apologise in advance for not submitting a bug report but rather asking for support.  I have a client that sent Omni USDT to my bitcoin.com multisig wallet.  that wallet has no support for this token so whilst I can see the transaction and that the token was delivered, I cannot access it.

can I use this tool to retrieve it, possibly sending it back to the sender? or elsewhere but where?

TIA - ekkis

**Comment by evias** [comment]
Yes, you will need to find out the derivation path(s) that your bitcoin.com multisig wallet uses.

Have a look at the README example case

**Comment by ekkis** [comment]
ok.  I installed PHP and tried to run the app but I get the following error:

> PHP Warning:  require(/Users/ekkis/dev/omni-recovery-tool/bootstrap/../../../autoload.php): failed to open stream: No such file or directory in /Users/ekkis/dev/omni-recovery-tool/bootstrap/autoload.php on line 22
> 
> Warning: require(/Users/ekkis/dev/omni-recovery-tool/bootstrap/../../../autoload.php): failed to open stream: No such file or directory in /Users/ekkis/dev/omni-recovery-tool/bootstrap/autoload.php on line 22
> PHP Fatal error:  require(): Failed opening required '/Users/ekkis/dev/omni-recovery-tool/bootstrap/../../../autoload.php' (include_path='.:/usr/local/Cellar/php/7.4.1/share/php/pear') in /Users/ekkis/dev/omni-recovery-tool/bootstrap/autoload.php on line 22
> 
> Fatal error: require(): Failed opening required '/Users/ekkis/dev/omni-recovery-tool/bootstrap/../../../autoload.php' (include_path='.:/usr/local/Cellar/php/7.4.1/share/php/pear') in /Users/ekkis/dev/omni-recovery-tool/bootstrap/autoload.php on line 22
> 

which is basically looking for an "autoload"er.  if I look in the `bootstrap/autoload.php` I see that *either* there should be a `vendor` directory project root, *or* the file gets sourced from above the project root (which, of course, will fail)
 
```php
if (file_exists(__DIR__.'/../vendor/autoload.php')) {
    require __DIR__.'/../vendor/autoload.php';
} else {
    require __DIR__.'/../../../autoload.php';
}
```

I'm missing something.  is there an installation guide for this tool?  I see a bunch of requirements but they seem optional

**Comment by ekkis** [comment]
I ask about an installation guide because it's not obvious how to install these requirements.  on OSX I installed php using `brew install php` but trying `brew install php7.1-bcmath` fails.  someone would have to package that and I'm not sure how PHP modules are generally installed

**Comment by evias** [comment]
interesting ; sorry again for the lag @ekkis ... I have not been watching this repo in a long time ; I use MAMP Pro on MacOS, which would let me install php extensions.

Would a docker container solve it for you? Docker generally comes in handy to circumvent any kind of machine wide dependencies, etc.
