### ISSUE TITLE
Is there a build command for this?

### ISSUE THREAD

**Issue by amritabithi** [evias/blockchain-cli#6]
Hello,

I am trying to run this again, and am wondering if I need to build these files locally before running the app?  The way it is set up now, running the script just calls a require() on itself and exits. 

Is there a command to build with Composer or Laravel?  Or how do you run when you use it?

**Comment by evias** [comment]
just run `composer install` ; then the `php application list` command will display all commands.

**Comment by amritabithi** [comment]
> just run `composer install` ; then the `php application list` command will display all commands.

Thank you so much for your help, I was able to get it installed and list the commands so I think that I am set now.

I did have to edit one line in the package.json file to use a lower case B in bitcoin, I have attached a screenshot of the error I got although I was able to fix that and finish building.  Thank you!

![image](https://user-images.githubusercontent.com/48937881/152712107-4a0833a9-3199-4826-a2df-956aa77028cc.png)
